### ISSUE TITLE
IFTTT not working

### ISSUE THREAD

**Issue by kalitk0** [zlalanne/home-assistant-config#1]
Hello,

Thank you for your great tutorial, I have setup it and all is working fine except the voice commands when I say clean the kitchen for example nothing happening. 

This is the log

Error processing webhook 7b99432c232b12234b4d777468ce31aed492d9ffae86a2af86460b6c0348bddb
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/webhook/__init__.py", line 97, in async_handle_webhook
    response = await webhook["handler"](hass, webhook_id, request)
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/helpers.py", line 231, in _handle_local_webhook
    payload = await request.json()
  File "/usr/src/homeassistant/homeassistant/util/aiohttp.py", line 67, in json
    return json.loads(self._text)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 43 (char 68)

Can you help please

**Comment by kalitk0** [comment]
OK I have another issue now

`2020-09-12 13:36:17 DEBUG (MainThread) [hass_nabucasa.iot] Received message:
{'handler': 'webhook',
 'msgid': 'b0c7958f-c322-412c-b63e-e9391fd05ff9',
 'payload': {'body': '{"action":"call_service",\n'
                     '"script":"script.vacuum_dispatch","room":"kitchen"\n'
                     '}',
             'cloudhook_id': '2a7f42d4ed4b43dd83dc06b62008c744',
             'headers': {'Accept': '*/*',
                         'Accept-Encoding': 'gzip, deflate',
                         'Cache-Control': 'no-cache',
                         'Content-Length': '78',
                         'Content-Type': 'application/json',
                         'Host': 'hooks.nabu.casa',
                         'Postman-Token': '72f25a07-0eb2-4b48-a0fc-95a046b59f17',
                         'User-Agent': 'PostmanRuntime/7.6.0',
                         'X-Forwarded-For': '212.233.184.225',
                         'X-Oc-Restadmin-Id': 'tujEA41NdYmnftLzoOJKNiAQMWZFXeMD'},
             'method': 'POST',
             'query': ''}}

2020-09-12 13:36:17 DEBUG (MainThread) [homeassistant.components.google_assistant.helpers] Received local message:
{'action': 'call_service',
 'room': 'kitchen',
 'script': 'script.vacuum_dispatch'}

2020-09-12 13:36:17 ERROR (MainThread) [homeassistant.components.webhook] Error processing webhook 7b99432c232b12234b4d777468ce31aed492d9ffae86a2af86460b6c0348bddb
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/webhook/__init__.py", line 97, in async_handle_webhook
    response = await webhook["handler"](hass, webhook_id, request)
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/helpers.py", line 239, in _handle_local_webhook
    result = await smart_home.async_handle_message(
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/smart_home.py", line 27, in async_handle_message
    config, user_id, source, message["requestId"], message.get("devices")
KeyError: 'requestId'
2020-09-12 13:36:17 DEBUG (MainThread) [hass_nabucasa.iot] Publishing message:
{'msgid': 'b0c7958f-c322-412c-b63e-e9391fd05ff9',
 'payload': {'body': None,
             'headers': {'Content-Type': 'application/octet-stream'},
             'status': 200}}`
